djcrm/urls.py
from re import template
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path, include
from leads.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LoginView.as_view(template_name="registration/login.html", redirect_authenticated_user=True), name='login'),
    path('leads/',  include('leads.urls', namespace="leads")),
    path('agents/',  include('agents.urls', namespace="agents")),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('company/', company_list, name='company'),
    path('apparats/', apparat_list, name='apparats'),
    path('number/', number_list, name='number'),
    path('atc/', atc_list, name='atc'),
    path('error/', error_page, name='error'),
    # path('company/', include('leads.urls', namespace="company"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.urls import path
from .views import *

app_name = "leads"

urlpatterns = [
    path('', lead_list, name='lead-list'),
    path('json/', LeadJsonView.as_view(), name='lead-list-json'),
    path('<int:pk>/', lead_detail, name='lead-detail'),
    path('<int:pk>/update/', lead_update, name='lead-update'),
    path('<int:pk>/delete/', lead_delete, name='lead-delete'),
    path('create/', lead_create, name='lead-create'),
    # path('phones/', phones, name='phones'),
    path('phone/', phone_number, name='lead-phone'),
    path('phone_create/', phone_number_create, name='lead-phone-create'),
    path('users/', user_list, name='users'),
    path('<int:pk>/user_update/', user_update, name='user_update'),
    path("<int:pk>/password_change/", password_change, name="password_change"),
    path('<int:pk>/user_delete/', user_delete, name='user_delete'),

    # path('<int:pk>/', CompanyDetailView.as_view(), name='company_detail'),
    path('create_company/', company_create, name='company_create'),
    path('<int:pk>/company_update/', company_update, name='company_update'),
    path('<int:pk>/company_delete/', company_delete, name='company_delete'),

    path('apparats_create/', apparat_create, name='apparats_create'),
    path('<int:pk>/apparats_update/', apparat_update, name='apparats_update'),
    path('<int:pk>/apparats_delete/', apparat_delete, name='apparats_delete'),

    path('atc_create/', atc_create, name='atc_create'),
    path('<int:pk>/atc_update/', atc_update, name='atc_update'),
    path('<int:pk>/atc_delete/', atc_delete, name='atc_delete'),

    path('create-number/', number_create, name='number-create'),
    path('<int:pk>/number_delete/', number_delete, name='number_delete'),
    # path('find-number/', number_list, name='number-find'),

    path('export_table/', export_to_csv, name='export_table'),
    path('export_to_exel/', export_to_exel, name='export_table_exel'),
]

leads/models.py
from email.policy import default
from random import choices
from secrets import choice
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
import re, uuid 
from uuid import uuid4
from django_extensions.db.fields import ShortUUIDField
from django.core.validators import MinLengthValidator
import shortuuid
import datetime



class User(AbstractUser):
    is_organisor = models.BooleanField(default=True)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Пользователь')

    def __str__(self):
        return self.user.username


class LeadManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()


class Lead(models.Model):

    TIMEZONE_CHOICES = (
        ('+8', 'Иркутск +8'),
        ('+3', 'Москва +3'),
        ('+7', 'Новосибирск +7'),
        ('+9', 'Якутск +9'),
    )
    CHOICES = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        ('7', '7'),
        ('8', '8'),
        ('9', '9'),
        ('10', '10'),
    )

    phone_number = models.OneToOneField("Number", unique=True, on_delete=models.PROTECT, verbose_name='Номер телефона')    
    mac_address = models.CharField(max_length=17, blank=True, verbose_name='MAC-Адрес', validators=[MinLengthValidator(12)])
    # mac_address = models.CharField(max_length=17,blank=True, verbose_name='MAC-Адрес', validators = [
    #     RegexValidator(
    #         regex=r'^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$',
    #         message = 'Не правильный ввод, пример ввода: 2c549188c9e3',
    #         code = 'invalid',
    #         inverse_match = False,
    #         flags = re.IGNORECASE
    #     )
    # ])
    first_name = models.CharField(max_length=20, blank=True, verbose_name='Имя')
    last_name = models.CharField(max_length=20, verbose_name='Фамилия')
    patronymic_name = models.CharField(max_length=20, blank=True, verbose_name='Отчество')
    phone_model = models.ManyToManyField("Apparats", verbose_name='Модель телефона')
    company = models.ManyToManyField("company", verbose_name='Компания')
    date_added = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')
    update_added = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    active = models.BooleanField(default=True)
    reservation = models.BooleanField(default=False, verbose_name='Зарезервировать')
    line = models.CharField(max_length=5,choices=CHOICES, default='1', verbose_name='Линия')
    atc = models.ManyToManyField("atc", verbose_name='ATC')
    passwd = ShortUUIDField(max_length=22, editable=False, default=shortuuid.uuid, verbose_name='Пароль')
    updated_user = models.CharField(max_length=20, blank=True, verbose_name='Обновил')
    created_user = models.CharField(max_length=20, blank=True, verbose_name='Добавил')
    record_calls = models.BooleanField(default=False, verbose_name='Запись разговоров') 
    external_line_access = models.CharField(
        max_length=20,
        choices=[
            ('локальные_МГ', 'Локальные МГ'),
            ('локальные_МГ_МН', 'Локальные МГ и МН'),
            ('локальные', 'Локальные'),
        ],
        default='локальные_МГ',
        verbose_name='Доступ к внешним линиям'
    )  # Выпадающий список
    call_forwarding = models.CharField(
        max_length=11,
        blank=True,
        null=True,
        validators=[RegexValidator(r'^\d{0,11}$', message="Поле должно содержать только цифры и быть не длиннее 11 символов.")],
        verbose_name='Переадресация'
    )  # Текстовое поле для переадресации

    timezone = models.CharField(
    max_length=3,
    choices=TIMEZONE_CHOICES,
    default='+8',  # Значение по умолчанию - Иркутск
    verbose_name='Часовой пояс'
    )

    class Meta:
        unique_together = ['mac_address', 'line']


    objects = LeadManager()

    def __str__(self):
        return f"{self.first_name} {self.last_name} {self.phone_number}"


class Company(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='Компании')

    def __str__(self):
        return self.name


class Apparats(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='Модель')

    def __str__(self):
        return self.name


class Number(models.Model):
    name = models.CharField(max_length=30, unique=True, verbose_name='Номер телефона')
    atc = models.ForeignKey('atc', on_delete=models.PROTECT, verbose_name='ATC')

    def __str__(self):
        return self.name


class Atc(models.Model):
    name = models.CharField(max_length=30, unique=True, verbose_name='Наименование')
    ip_address = models.CharField(max_length=30, verbose_name='IP адрес')

    def __str__(self):
        return self.name

leads/forms.py
from dataclasses import Field
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from .models import Lead, Company, Apparats, Number, Atc
from itertools import chain
from django.db.models import Count
from django.forms import inlineformset_factory
from crispy_forms.helper import FormHelper, Layout
from crispy_forms.layout import Fieldset,Field

User = get_user_model()

class LeadCreateModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = '__all__'

    def __init__(self,*args,**kwargs):
        super(LeadCreateModelForm, self).__init__(*args,**kwargs)
        self.fields['atc'].empty_label = "ATC не выбрана"
        self.fields['phone_number'].empty_label = "номер телефона не выбран"
        self.fields['company'].empty_label = "компания не выбрана"
        self.fields['phone_model'].empty_label = "модель телефона не выбрана"
        

    def clean_first_name(self):
        data = self.cleaned_data["first_name"]

        return data



    def clean(self):
        pass


class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = '__all__'
        

    def clean_first_name(self):
        data = self.cleaned_data["first_name"]

        return data

    def clean(self):
        pass


class LeadDelModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ()
        

    def clean_first_name(self):
        data = self.cleaned_data["first_name"]

        return data

    def clean(self):
        
        pass


class CompanyDelModelForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ()
        

    def clean_first_name(self):
        data = self.cleaned_data["first_name"]

        return data

    def clean(self):
        pass


class ApparatDelModelForm(forms.ModelForm):
    class Meta:
        model = Apparats
        fields = ()
        

    def clean_first_name(self):
        data = self.cleaned_data["first_name"]

        return data

    def clean(self):
        pass


class NumberDelModelForm(forms.ModelForm):
    class Meta:
        model = Apparats
        fields = ()
        

    def clean_first_name(self):
        data = self.cleaned_data["first_name"]

        return data

    def clean(self):
        pass        


class UserModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'username',
            'is_superuser',
            'is_active',
            'first_name',
            'last_name',
        )
        

    def clean_first_name(self):
        data = self.cleaned_data["first_name"]

        return data

    def clean(self):
        pass


class UserDelModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ()
        

    def clean_first_name(self):
        data = self.cleaned_data["first_name"]

        return data

    def clean(self):
        pass



class SetPasswordForm(SetPasswordForm):
    class Meta:
        model = get_user_model()
        fields = ['new_password1', 'new_password2']


    def clean_first_name(self):
        data = self.cleaned_data["first_name"]

        return data

    def clean(self):
        pass

        

class CompanyModelForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = (
            'name',
        )


    def clean_first_name(self):
        data = self.cleaned_data["first_name"]
        return data


    def clean(self):
        
        pass



class ApparatModelForm(forms.ModelForm):
    class Meta:
        model = Apparats
        fields = (
            'name',
        )


    def clean_first_name(self):
        data = self.cleaned_data["first_name"]
        return data


    def clean(self):
        pass



class NumberModelForm(forms.ModelForm):
    class Meta:
        model = Number
        fields = (
            'name',
            'atc',
        )


    def clean_first_name(self):
        data = self.cleaned_data["first_name"]
        return data


    def clean(self):
        pass



class AtcModelForm(forms.ModelForm):
    class Meta:
        model = Atc
        fields = (
            'name',
            'ip_address',
        )


    def clean_first_name(self):
        data = self.cleaned_data["first_name"]
        return data


    def clean(self):
        pass



class LeadForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age = forms.IntegerField(min_value=0)


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "username",
            "is_superuser",
            "first_name",
            "last_name",
        )
        field_classes = {'username': UsernameField}
        

leads/templates/leads/apparats_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">Оператор</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name }} {{ lead.last_name }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'leads:apparats_update' lead.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Обновляемая информация
                </a>
            </div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Готово</button>
            </form>
            <div class="mt-5 py-5 border-t border-gray-200">
              <a href="{% url 'leads:apparats_delete' lead.pk %}" class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                  Удалить
              </a>
          </div>
            </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

leads/templates/leads/atc.html
{% extends "base.html" %}

{% block content %}    

<section class="text-gray-700 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-800">ATC</h1>
            </div>
            {% if request.user.is_organisor %}
            <div>
                <a class="text-gray-500 hover:text-blue-500" href="{% url 'leads:atc_create' %}">
                    Добавить
                </a>
            </div>
            {% endif %}
        </div>
        
        <div class="flex flex-col w-full" style="width: 10000cm; margin-left: -50px;">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Сервер
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                IP адрес
                            </th>
                            <th scope="col" class="relative px-6 py-3">
                            <span class="sr-only">Изменить</span>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <div class="form-error"> {{ form.non_field_errors }} </div>
                        {% for lead in leads %}
                            <tr class="bg-white">
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ lead.name }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ lead.ip_address }}
                                </td>
                                    <div class="form-error">{{form.errors}} </div>
                                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                    <a href="{% url 'leads:atc_update' lead.pk %}" class="text-indigo-600 hover:text-indigo-900">
                                        Изменить
                                    </a>
                                </td>
                                
                            </tr>

                        {% empty %}

                        <p>На данный момент нет никаких позиций</p>

                        {% endfor %}
                    </tbody>
                </table>
                </div>
            </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

leads/templates/leads/company_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <div class="w-full flex items-center justify-between space-x-6">
                    <div class="flex-1 truncate">
                        <div class="flex items-center space-x-3">
                            <h3 class="text-3xl text-gray-900 font-medium truncate">{{ lead.first_name }} {{ lead.last_name }}</h3>
                        </div>
                        <p class="mt-1 text-xl text-gray-500 truncate">{{ lead.description }}</p>
                    </div>
                </div>
                <div class="flex mb-4">
                    <a href="{% url 'leads:company_update' company.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Обновляемая информация
                    </a>    
                </div>
                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Фамилия</span>
                    <span class="ml-auto text-gray-900">{{ lead.last_name }}</span>
                </div>
                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Имя</span>
                    <span class="ml-auto text-gray-900">{{ lead.first_name }}</span>
                </div>
                <div class="flex border-t border-b mb-6 border-gray-300 py-2">
                    <span class="text-gray-500">Отчество</span>
                    <span class="ml-auto text-gray-900">{{ lead.patronymic_name }}</span>
                </div>
            </div>

        <!-- <a href="{% url 'leads:lead-followup-create' lead.pk %}" class="text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Add a followup</a> -->

        </div>

        {% for followup in lead.followups.all %}
            <div class="mt-5 shadow px-4 sm:px-6">
                <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
                    <dt class="text-sm font-medium text-gray-500">
                    Notes (<a href="{% url 'leads:lead-followup-update' followup.pk %}" class="text-blue-500 hover:text-blue-700">update</a>)
                    </dt>
                    <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    {{ followup.notes }}
                    </dd>
                </div>
                {% if followup.file %}
                    <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
                        <dt class="text-sm font-medium text-gray-500">
                        Attachments
                        </dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                        <ul class="border border-gray-200 rounded-md divide-y divide-gray-200">
                            <li class="pl-3 pr-4 py-3 flex items-center justify-between text-sm">
                                <div class="w-0 flex-1 flex items-center">
                                    <!-- Heroicon name: paper-clip -->
                                    <svg class="flex-shrink-0 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                    <path fill-rule="evenodd" d="M8 4a3 3 0 00-3 3v4a5 5 0 0010 0V7a1 1 0 112 0v4a7 7 0 11-14 0V7a5 5 0 0110 0v4a3 3 0 11-6 0V7a1 1 0 012 0v4a1 1 0 102 0V7a3 3 0 00-3-3z" clip-rule="evenodd" />
                                    </svg>
                                    <span class="ml-2 flex-1 w-0 truncate">
                                    {{ followup.file.name }}
                                    </span>
                                </div>
                                <div class="ml-4 flex-shrink-0">
                                    <a href="{{ followup.file.url }}" download class="font-medium text-indigo-600 hover:text-indigo-500">
                                    Download
                                    </a>
                                </div>
                            </li>
                        </ul>
                        </dd>
                    </div>
                {% endif %}
            </div>
        {% endfor %}


        

    </div>
  </section>
{% endblock content %}

leads/templates/leads/company_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">Оператор</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name }} {{ lead.last_name }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'leads:company_update' company.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Обновляемая информация
                </a>
            </div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Готово</button>
            </form>
            <div class="mt-5 py-5 border-t border-gray-200">
              <a href="{% url 'leads:company_delete' company.pk %}" class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                  Удалить
              </a>
          </div>
            </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

leads/templates/leads/lead_atc_filtering.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'leads:lead-list' %}">Вернуться к таблице</a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Создание новой позиции</h1>
    </div>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Далее
        </button>
    </form>
</div>

{% endblock content %}

leads/templates/leads/lead_update.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto" style="margin-top:-100px;">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-gray-900 text-3xl title-font font-medium mb-4">Телефоны (MAC)</h2>
            
            <div class="flex mb-4">
                <a href="{% url 'leads:lead-update' lead.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Обновляемая информация
                </a>
                <!-- Добавляем ссылку на обзор -->
                <a href="{% url 'leads:lead-detail' lead.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1 ml-4">
                    Обзор
                </a>
            </div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="row">
                    <div class="col-6">
                        {{ form.atc | as_crispy_field }}
                    </div>
                    <div class="col-6">
                        {{ form.phone_number | as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-2">
                        {{ form.reservation | as_crispy_field }}
                    </div>
                    <div class="col-6">
                        {{ form.mac_address | as_crispy_field }}
                    </div>
                    <div class="col-4">
                        {{ form.line | as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-4">
                        {{ form.last_name | as_crispy_field }}
                    </div>
                    <div class="col-4">
                        {{ form.first_name | as_crispy_field }}
                    </div>
                    <div class="col-4">
                        {{ form.patronymic_name | as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-5">
                        {{ form.phone_model | as_crispy_field }}
                    </div>
                    <div class="col-5">
                        {{ form.company | as_crispy_field }}
                    </div>
                    <div class="col-2">
                        {{ form.active | as_crispy_field }}
                    </div>
                </div>

                <!-- Новый блок для новых полей -->
                <div class="row mt-4">
                    <div class="col-4">
                        {{ form.record_calls | as_crispy_field }}
                    </div>
                    <div class="col-4">
                        {{ form.external_line_access | as_crispy_field }}
                    </div>
                    <div class="col-4">
                        {{ form.call_forwarding | as_crispy_field }}
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-6">
                        {{ form.timezone | as_crispy_field }}
                    </div>
                </div>
                <div class="d-flex justify-content-center">
                    <button type='submit' id="buttonStyle"
                        class="col-6 text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
                        Готово
                    </button>
                </div>

            </form>
            <div class="mt-5 py-5 border-t border-gray-200">
                <a href="{% url 'leads:lead-delete' lead.pk %}" class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                    Удалить
                </a>
            </div>
        </div>
      </div>
    </div>
  </section>

  <script>
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    const csrftoken = getCookie('csrftoken');

    let atc_field = document.getElementById("div_id_atc")
    let atc_name = document.getElementById("div_id_atc").querySelector('[selected]').textContent;
    let current_number = document.getElementById("div_id_phone_number").querySelector('[selected]').textContent;
    let number_field = document.querySelector("div.relative select[name='phone_number']")
    atc_field.addEventListener("change", getAtcId)


    function getAtcId(e) {
        let atc_id = e.target.value


        const data = { id: atc_id, atc_name: atc_name, current_number };

        let url = " {% url 'leads:lead-phone' %} "

        fetch(url, {
            method: 'POST', // or 'PUT'
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': csrftoken
            },
            body: JSON.stringify(data),
        })
            .then((response) => response.json())

            .then((data) => {
                console.log('Success:', data);

                if (data.length != 0) {
                    number_field.innerHTML = `<option value="${data[0]["id"]}" id="number-id-field">${data[0]["name"]}</option>`


                    for (let i = 1; i < data.length; i++) {
                        number_field.innerHTML += `<option value="${data[i]["id"]}" id="number-id-field">${data[i]["name"]}</option>`
                    }

                } else {
                    number_field.innerHTML = '<option value="" id="number-id-field">Нет свободных номеров</option>'

                }

            })
            .catch((error) => {
                console.error('Error:', error);
            });

    }
</script>

{% endblock content %}