djcrm/urls.py
from re import template
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path, include
from leads.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LoginView.as_view(template_name="registration/login.html", redirect_authenticated_user=True), name='login'),
    path('leads/',  include('leads.urls', namespace="leads")),
    path('agents/',  include('agents.urls', namespace="agents")),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('company/', company_list, name='company'),
    path('apparats/', apparat_list, name='apparats'),
    path('number/', number_list, name='number'),
    path('atc/', atc_list, name='atc'),
    path('error/', error_page, name='error'),
    # path('company/', include('leads.urls', namespace="company"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.urls import path
from .views import *

app_name = "leads"

urlpatterns = [
    path('', lead_list, name='lead-list'),
    path('json/', LeadJsonView.as_view(), name='lead-list-json'),
    path('<int:pk>/', lead_detail, name='lead-detail'),
    path('<int:pk>/update/', lead_update, name='lead-update'),
    path('<int:pk>/delete/', lead_delete, name='lead-delete'),
    path('create/', lead_create, name='lead-create'),
    # path('phones/', phones, name='phones'),
    path('phone/', phone_number, name='lead-phone'),
    path('phone_create/', phone_number_create, name='lead-phone-create'),
    path('users/', user_list, name='users'),
    path('<int:pk>/user_update/', user_update, name='user_update'),
    path("<int:pk>/password_change/", password_change, name="password_change"),
    path('<int:pk>/user_delete/', user_delete, name='user_delete'),

    # path('<int:pk>/', CompanyDetailView.as_view(), name='company_detail'),
    path('create_company/', company_create, name='company_create'),
    path('<int:pk>/company_update/', company_update, name='company_update'),
    path('<int:pk>/company_delete/', company_delete, name='company_delete'),

    path('apparats_create/', apparat_create, name='apparats_create'),
    path('<int:pk>/apparats_update/', apparat_update, name='apparats_update'),
    path('<int:pk>/apparats_delete/', apparat_delete, name='apparats_delete'),

    path('atc_create/', atc_create, name='atc_create'),
    path('<int:pk>/atc_update/', atc_update, name='atc_update'),
    path('<int:pk>/atc_delete/', atc_delete, name='atc_delete'),

    path('create-number/', number_create, name='number-create'),
    path('<int:pk>/number_delete/', number_delete, name='number_delete'),
    # path('find-number/', number_list, name='number-find'),

    path('export_table/', export_to_csv, name='export_table'),
    path('export_to_exel/', export_to_exel, name='export_table_exel'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="shortcut icon" href="{% static 'images/dashboard.svg' %}" type="image/svg">   
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Provisioning system</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    
    <!-- HTMX -->
    <script src="https://unpkg.com/htmx.org@1.6.0"></script>
</head>
<body>
    <div class="max-w-7xl mx-auto">
        {% include 'navbar.html' %}
        {% include 'messages.html' %}
        {% block content %}
        {% endblock content %}
    </div>
    {% include "scripts.html" %}
</body>
</html>

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="text-gray-700 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
            CRM Dashboard
        </h1>
    
        <div class="flex flex-wrap -m-4 text-center">
            <div class="p-4 md:w-1/3 sm:w-1/2 w-full">
                <div class="border-2 border-gray-200 px-4 py-6 rounded-lg">
                <h2 class="title-font font-medium text-3xl text-gray-900">{{ total_lead_count }}</h2>
                <p class="leading-relaxed">Total Leads</p>
                </div>
            </div>
            <div class="p-4 md:w-1/3 sm:w-1/2 w-full">
                <div class="border-2 border-gray-200 px-4 py-6 rounded-lg">
                <h2 class="title-font font-medium text-3xl text-gray-900">{{ total_in_past30 }}</h2>
                <p class="leading-relaxed">Leads added in last 30 days</p>
                </div>
            </div>
            <div class="p-4 md:w-1/3 sm:w-1/2 w-full">
                <div class="border-2 border-gray-200 px-4 py-6 rounded-lg">
                <h2 class="title-font font-medium text-3xl text-gray-900">{{ converted_in_past30 }}</h2>
                <p class="leading-relaxed">Converted in last 30 days</p>
                </div>
            </div>
        </div>
        
      </div>
    </div>
</section>
{% endblock content %}

templates/error.html
<div class="max-w-lg mx-auto">
    <div class="py-5 border-b border-gray-200">
        <input class="hover:text-blue-500" type="button" onclick="history.back();" value="Вернуться назад"/>
    </div>
    <h1 class="text-3xl text-gray-800">Что то пошло не так.</h1>
    <h1 class="text-3xl text-gray-800">{{error}} </h1>
    <h1 class="text-3xl text-gray-800"> {% for x in mac %} {{ x }} {% endfor %} </h1>

templates/error_atc.html
<div class="max-w-lg mx-auto">
    <div class="py-5 border-b border-gray-200">
        
        <input class="hover:text-blue-500" type="button" onclick="history.back();" value="Вернуться назад"/>
    </div>
    <h1 class="text-3xl text-gray-800">Данную ATC нельзя удалить так как она используется в Телефоны(MAC) </h1>
    

templates/error_company.html
<div class="max-w-lg mx-auto">
    <div class="py-5 border-b border-gray-200">
        <input class="hover:text-blue-500" type="button" onclick="history.back();" value="Вернуться назад"/>
    </div>
    <h1 class="text-3xl text-gray-800">Что то пошло не так.</h1>
    <h1 class="text-3xl text-gray-800">Данная компания используется в Телефоны(MAC)</h1>

templates/error_mac.html
<div class="max-w-lg mx-auto">
    <div class="py-5 border-b border-gray-200">
        <input class="hover:text-blue-500" type="button" onclick="history.back();" value="Вернуться назад"/>
    </div>
    <h1 class="text-3xl text-gray-800">Что то пошло не так.</h1>
    <h1 class="text-3xl text-gray-800">Поле MAC адреса осталось пустым</h1>

templates/error_mac_failed.html
<div class="max-w-lg mx-auto">
    <div class="py-5 border-b border-gray-200">
        <input class="hover:text-blue-500" type="button" onclick="history.back();" value="Вернуться назад"/>
    </div>
    <h1 class="text-3xl text-gray-800">Что то пошло не так.</h1>
    <h1 class="text-3xl text-gray-800">Поле MAC адреса было введено неверно</h1>

templates/error_mac_type_failed.html
<div class="max-w-lg mx-auto">
    <div class="py-5 border-b border-gray-200">
        <input class="hover:text-blue-500" type="button" onclick="history.back();" value="Вернуться назад"/>
    </div>
    <h1 class="text-3xl text-gray-800">Что то пошло не так.</h1>
    <h1 class="text-3xl text-gray-800">В поле MAC адреса былы введены недопустимые символы </h1>

templates/error_model.html
<div class="max-w-lg mx-auto">
    <div class="py-5 border-b border-gray-200">
        <input class="hover:text-blue-500" type="button" onclick="history.back();" value="Вернуться назад"/>
    </div>
    <h1 class="text-3xl text-gray-800">Данную модель нельзя удалить так как она используется в Телефоны(MAC)</h1>

templates/error_number.html
<div class="max-w-lg mx-auto">
    <div class="py-5 border-b border-gray-200">
        <input class="hover:text-blue-500" type="button" onclick="history.back();" value="Вернуться назад"/>
    </div>
    <h1 class="text-3xl text-gray-800">Данный номер телефона нельзя удалить так как он используется в Телефоны(MAC)</h1>

templates/landing.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="text-gray-700 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="{% static 'images/dashboard.svg' %}">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
          Provisioning systems
        </h1>
        <p class="mb-8 leading-relaxed">
            cистема предназначеня для контроля телефонных клиентов
        </p>
        <div class="flex justify-center">
          <a href="{% url 'login' %}" class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">
            Давайте начнем !
          </a>
        </div>
      </div>
    </div>
</section>
{% endblock content %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="p-4 border-l-4
        {% if message.tags == 'success' %}
        bg-green-50 border-green-400
        {% elif message.tags == 'info' %}
        bg-blue-50 border-blue-400
        {% elif message.tags == 'warning' %}
        bg-yellow-50 border-yellow-400
        {% else %}
        bg-red-50 border-red-400
        {% endif %}
        ">
            <p class="text-sm
            {% if message.tags == 'success' %}
            text-green-700
            {% elif message.tags == 'info' %}
            text-blue-700
            {% elif message.tags == 'warning' %}
            text-yellow-700
            {% else %}
            text-red-700
            {% endif %}
            ">
                {{ message }}
            </p>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<header class="text-gray-700 body-font">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
      <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
        {% if user.is_superuser %}
        <div>
          <a class="hover:text-blue-500" style="margin-left: -140px;" href="{% url 'company' %}"> | &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Компании</a>
      </div>
        <div>
        <a class="hover:text-blue-500" href="{% url 'apparats' %}"> Модели телефонов&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
      </div>
        <div>
        <a class="hover:text-blue-500" href="{% url 'number' %}"> Нумерация &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
      </div>
      <div>
        <a class="hover:text-blue-500" href="{% url 'atc' %}">ATC &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </a>
      </div> 
      <div>
        <a class="hover:text-blue-500" href="{% url 'leads:lead-list' %}">Телефоны (MAC)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
      </div> 
      <div>
        <a class="hover:text-blue-500" href="{% url 'leads:users' %}"> | &nbsp;&nbsp;&nbsp; Контроль пользователей &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | </a>
      </div>       
      {% endif %}
        {% if not request.user.is_authenticated %}
          
        {% else %}
          {% if request.user.is_organisor %}
          
          {% endif %}
          
        {% endif %}
      </nav>
      {% if request.user.is_authenticated %}
      &nbsp;&nbsp;&nbsp;&nbsp;Вы вошли как: {{ request.user.username }}
        <a href="{% url 'logout' %}" class="ml-3 inline-flex items-center bg-gray-200 border-0 py-1 px-3 focus:outline-none hover:bg-gray-300 rounded text-base mt-4 md:mt-0">
          Выйти
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
        </a>
      {% else %}
      
    
      </a>
      {% endif %}
    </div>
  
</header>

templates/scripts.html
{% load static %}

<script src="{% static 'js/main.js' %}"></script>